-----ENTIDAD FEDERATIVA
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (1, 'Aguascalientes');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (2, 'Baja California');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (3, 'Baja California Sur');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (4, 'Campeche');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (5, 'Coahuila de Zaragoza');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (6, 'Colima');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (7, 'Chiapas');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (8, 'Chihuahua');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (9, 'Ciudad de México');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (10, 'Durango');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (11, 'Guanajuato');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (12, 'Guerrero');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (13, 'Hidalgo');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (14, 'Jalisco');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (15, 'Estado de México');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (16, 'Michoacán de Ocampo');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (17, 'Morelos');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (18, 'Nayarit');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (19, 'Nuevo León');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (20, 'Oaxaca');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (21, 'Puebla');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (22, 'Querétaro');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (23, 'Quintana Roo');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (24, 'San Luis Potosí');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (25, 'Sinaloa');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (26, 'Sonora');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (27, 'Tabasco');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (28, 'Tamaulipas');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (29, 'Tlaxcala');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (30, 'Veracruz de Ignacio de la Llave');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (31, 'Yucatán');
INSERT INTO ENTIDADFEDERATIVA (ID, DESCRIPCION) 
VALUES (32, 'Zacatecas');

COMMIT;

