-- ----LIMPIEZA DE DATOS PREVIOS
---- RECORDAR COLONIA Y CODIGO POSTAL AGREGAR
    DELETE FROM VOTO;
    DELETE FROM PERSONACANDIDATURA;
    DELETE FROM CANDIDATURA;
    DELETE FROM ELECTOR;
    DELETE FROM PROCESOLUGAR;
    DELETE FROM INSTANCIADEPROCESO;
    DELETE FROM PARTIDO;
    DELETE FROM VISUAL;
    DELETE FROM PERSONADOMICILIO;
    DELETE FROM DOMICILIO;
    DELETE FROM RELACIONFAMILIAR;
    DELETE FROM PERSONA;
    COMMIT;

-- ----PERSONA 
-- PADRES PREVIAMENTE EXISTENTES, TIENEN UN HIJO
DECLARE
    v_id_padre NUMBER;
    v_id_madre NUMBER;
    v_id_hijo NUMBER;
    v_id_domicilio_nacimiento NUMBER;
    v_id_domicilio_residencia NUMBER;
    v_id_logo NUMBER;
    v_id_partido NUMBER;
    v_id_instancia1 NUMBER;
    v_id_instancia2 NUMBER;
    v_id_candidatura1 NUMBER;
    v_id_candidatura2 NUMBER;
    
BEGIN
    INSERT INTO PERSONA(NOMBRE, APELLIDOPATERNO, APELLIDOMATERNO, FECHADENACIMIENTO)
    VALUES('JUAN JOSE', 'RIVERA', 'VALDES', TO_DATE('1967-04-20','YYYY-MM-DD'))
    RETURNING ID INTO v_id_padre;

    INSERT INTO PERSONA(NOMBRE, APELLIDOPATERNO, APELLIDOMATERNO, FECHADENACIMIENTO)
    VALUES('XOCHITL', 'VALDES', 'RIVERA', TO_DATE('1967-06-29','YYYY-MM-DD'))
    RETURNING ID INTO v_id_madre;

    INSERT INTO PERSONA(NOMBRE, APELLIDOPATERNO, APELLIDOMATERNO, FECHADENACIMIENTO)
    VALUES('JOSE ANTONIO', 'RIVERA', 'VALDES', TO_DATE('2000-04-15','YYYY-MM-DD'))
    RETURNING ID INTO v_id_hijo;

    COMMIT;

    -- ----RELACION FAMILIAR
    INSERT INTO RELACIONFAMILIAR(IDDEPERSONA, IDDEMADRE, IDDEPADRE)
    VALUES(v_id_hijo, v_id_madre, v_id_padre);

    INSERT INTO RELACIONFAMILIAR(IDDEPERSONA)
    VALUES(v_id_madre);

    INSERT INTO RELACIONFAMILIAR(IDDEPERSONA)
    VALUES(v_id_padre);

    COMMIT;
    
    -- ----DOMICILIO 
-- ------A MOMENTO DE NACIMIENTO O REGISTRO CIVIL
    INSERT INTO DOMICILIO(IDDEFEDERATIVA, IDDEMUNICIPIO)
    VALUES (15, 151060001)
    RETURNING ID INTO v_id_domicilio_nacimiento;

    INSERT INTO PERSONADOMICILIO(IDDEPERSONA, IDDEDOMICILIO, IDDETIPODEDOMICILIO, FECHADEINICIO)
    VALUES (v_id_hijo, v_id_domicilio_nacimiento, 1, TO_DATE('2000-04-25','YYYY-MM-DD'));

    COMMIT;

    -- ----A MOMENTO DE CAMBIO DE RESIDENCIA A SOLTEROS
    INSERT INTO DOMICILIO(IDDEFEDERATIVA, IDDEMUNICIPIO, IDDELOCALIDAD, NUMEXT, CALLE)
    VALUES (15, 151060001, 185161, 423, 'DIVISION DEL NORTE')
    RETURNING ID INTO v_id_domicilio_residencia;

    INSERT INTO PERSONADOMICILIO(IDDEPERSONA, IDDEDOMICILIO, IDDETIPODEDOMICILIO, FECHADEINICIO)
    VALUES (v_id_padre, v_id_domicilio_residencia, 2, TO_DATE('2017-06-25','YYYY-MM-DD'));

    INSERT INTO PERSONADOMICILIO(IDDEPERSONA, IDDEDOMICILIO, IDDETIPODEDOMICILIO, FECHADEINICIO)
    VALUES (v_id_madre, v_id_domicilio_residencia, 2, TO_DATE('2017-06-25','YYYY-MM-DD'));

    INSERT INTO PERSONADOMICILIO(IDDEPERSONA, IDDEDOMICILIO, IDDETIPODEDOMICILIO, FECHADEINICIO)
    VALUES (v_id_hijo, v_id_domicilio_residencia, 2, TO_DATE('2018-09-13','YYYY-MM-DD'));

    COMMIT;
    -- ---------------------PROCESO ELECTORAL 
-- -----NACE UN PARTIDO 
    
    INSERT INTO VISUAL(CONTENIDO)
    VALUES ('LOGO DEL PAN')
    RETURNING ID INTO v_id_logo;

    INSERT INTO PARTIDO(DENOMINACION, SIGLAS, IDDELOGO, FECHADEINICIO)
    VALUES ('PARTIDO ACCION NACIONAL', 'PAN', v_id_logo, TO_DATE('1939-09-16','YYYY-MM-DD'))
    RETURNING ID INTO v_id_partido;

    -- -----INICIA UNA TEMPORADA ELECTORAL PARA PRESIDENCIA
    INSERT INTO INSTANCIADEPROCESO(IDDEPROCESO, IDDENIVEL, GANADORESNUM, FECHAHORADEINICIO, FECHAHORADEFIN)
    VALUES (1, 1, 1, TO_DATE('2024-12-17 00:00:00','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-17 23:59:59','YYYY-MM-DD HH24:MI:SS'))
    RETURNING ID INTO v_id_instancia1;

    INSERT INTO INSTANCIADEPROCESO(IDDEPROCESO, IDDENIVEL, GANADORESNUM, FECHAHORADEINICIO, FECHAHORADEFIN)
    VALUES (4, 2, 1, TO_DATE('2024-12-17 00:00:00','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-17 23:59:59','YYYY-MM-DD HH24:MI:SS'))
    RETURNING ID INTO v_id_instancia2;

    INSERT INTO PROCESOLUGAR(IDDEINSTANCIADEPROCESO, IDDENIVEL, IDDEENTIDAD)
    VALUES (v_id_instancia2, 2, 15);

    -- -----TODOS VAN A SU REGISTRO ELECTORAL
    INSERT INTO ELECTOR(IDDEPERSONA)
    VALUES (v_id_padre);

    INSERT INTO ELECTOR(IDDEPERSONA)
    VALUES (v_id_madre);

    INSERT INTO ELECTOR(IDDEPERSONA)
    VALUES (v_id_hijo);

    -- -----EL HIJO DECIDE SER CANDIDATO
    INSERT INTO CANDIDATURA(IDDEINSTANCIADEPROCESO, IDDEPARTIDO)
    VALUES (v_id_instancia1, v_id_partido)
    RETURNING ID INTO v_id_candidatura1;

    INSERT INTO PERSONACANDIDATURA(IDDEPERSONA, IDDECANDIDATURA, FECHAHORADEINICIO, FECHAHORADEFIN)
    VALUES (v_id_hijo, v_id_candidatura1, TO_DATE('2024-08-16 07:00:00','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-17 23:59:59','YYYY-MM-DD HH24:MI:SS'));

    INSERT INTO CANDIDATURA(IDDEINSTANCIADEPROCESO, IDDEPARTIDO)
    VALUES (v_id_instancia2, v_id_partido)
    RETURNING ID INTO v_id_candidatura2;

    INSERT INTO PERSONACANDIDATURA(IDDEPERSONA, IDDECANDIDATURA, FECHAHORADEINICIO, FECHAHORADEFIN)
    VALUES (v_id_padre, v_id_candidatura2, TO_DATE('2024-08-16 07:00:00','YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-17 23:59:59','YYYY-MM-DD HH24:MI:SS'));

    -- -----LLEGA EL DIA DE LAS ELECCIONES
    INSERT INTO VOTO(IDDEINSTANCIADEPROCESO, IDDECANDIDATURA)
    VALUES (v_id_instancia1, v_id_candidatura1);

    INSERT INTO VOTO(IDDEINSTANCIADEPROCESO, IDDECANDIDATURA)
    VALUES (v_id_instancia2, v_id_candidatura2);
    
    INSERT INTO VOTO(IDDEINSTANCIADEPROCESO, IDDECANDIDATURA)
    VALUES (v_id_instancia1, v_id_candidatura1);

    INSERT INTO VOTO(IDDEINSTANCIADEPROCESO, IDDECANDIDATURA)
    VALUES (v_id_instancia2, v_id_candidatura2);
    
    INSERT INTO VOTO(IDDEINSTANCIADEPROCESO, IDDECANDIDATURA)
    VALUES (v_id_instancia1, v_id_candidatura1);

    INSERT INTO VOTO(IDDEINSTANCIADEPROCESO, IDDECANDIDATURA)
    VALUES (v_id_instancia2, v_id_candidatura2);
    
    INSERT INTO VOTO(IDDEINSTANCIADEPROCESO, IDDECANDIDATURA)
    VALUES (v_id_instancia1, v_id_candidatura1);
    
    INSERT INTO VOTO(IDDEINSTANCIADEPROCESO, IDDECANDIDATURA)
    VALUES (v_id_instancia1, v_id_candidatura1);

    COMMIT;

END;
/

