-- Desactivar restricciones de claves foráneas temporalmente
BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET CONSTRAINTS = DEFERRED';
END;
/

-- Eliminar tablas en orden inverso de las dependencias
DROP TABLE Voto CASCADE CONSTRAINTS;
----DROP TABLE PersonaCandidatura CASCADE CONSTRAINTS; -- DEJO DE EXISTIR EN UNA VERSION ANTERIOR
DROP TABLE ElectorCandidatura CASCADE CONSTRAINTS;
DROP TABLE ProcesoLugar CASCADE CONSTRAINTS;-----NUEVA
DROP TABLE Elector CASCADE CONSTRAINTS;
DROP TABLE Candidatura CASCADE CONSTRAINTS;
DROP TABLE TipoDeDomicilio CASCADE CONSTRAINTS; --Agregado posteriormente 
DROP TABLE RelacionFamiliar CASCADE CONSTRAINTS;
DROP TABLE PersonaDomicilio CASCADE CONSTRAINTS;
DROP TABLE Domicilio CASCADE CONSTRAINTS;
DROP TABLE ElectorInstancia CASCADE CONSTRAINTS;
--DROP TABLE Postal CASCADE CONSTRAINTS; se uso en la version anterior del sistema
DROP TABLE Localidad CASCADE CONSTRAINTS;
DROP TABLE Visual CASCADE CONSTRAINTS;------NUEVA
--DROP TABLE Colonia CASCADE CONSTRAINTS;, esta se uso en la version anterior del sistema
DROP TABLE Postal CASCADE CONSTRAINTS;
DROP TABLE Colonia CASCADE CONSTRAINTS;
DROP TABLE Municipio CASCADE CONSTRAINTS;
DROP TABLE EntidadFederativa CASCADE CONSTRAINTS;
---DROP TABLE NivelProceso CASCADE CONSTRAINTS;, esta se uso en la version anterior del sistema
DROP TABLE InstanciaDeProceso CASCADE CONSTRAINTS;
DROP TABLE Nivel CASCADE CONSTRAINTS;
DROP TABLE Proceso CASCADE CONSTRAINTS;
DROP TABLE Partido CASCADE CONSTRAINTS;
DROP TABLE Persona CASCADE CONSTRAINTS;
DROP TABLE RecursoVigente CASCADE CONSTRAINTS;
DROP TABLE TipoDeVisual CASCADE CONSTRAINTS;





--PROCURAR NO ELIMINAR 
--

--Crea las tablas

--Registro civil

--Registro civil ---- Sistema geografico

CREATE TABLE EntidadFederativa (
    Id INT PRIMARY KEY,
    descripcion VARCHAR2(255) NOT NULL
);

CREATE TABLE Municipio (
    Id INT PRIMARY KEY,
    IdDeEntidad INT NOT NULL,
    descripcion VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_municipio_federativa FOREIGN KEY (IdDeEntidad) REFERENCES EntidadFederativa(Id)
);

---ESTE NOMBRE SE VA A TENER QUE CAMBIAR EN ECLIPSE
CREATE TABLE Localidad (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdDeMunicipio INT NOT NULL,
    descripcion VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_localidad_municipio FOREIGN KEY (IdDeMunicipio) REFERENCES Municipio(Id)
);

CREATE TABLE Colonia (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdDeMunicipio INT NOT NULL,
    descripcion VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_colonia_municipio FOREIGN KEY (IdDeMunicipio) REFERENCES Municipio(Id)
);

CREATE TABLE Postal (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdDeColonia INT NOT NULL,
    descripcion VARCHAR2(255) NOT NULL,
    CONSTRAINT fk_postal_colonia FOREIGN KEY (IdDeColonia) REFERENCES Colonia(Id)
);

--SE USO EN VERSION ANTERIOR
--CREATE TABLE Postal (
--    Id INT PRIMARY KEY,
--    IdDeAsentamiento INT NOT NULL,
--    descripcion VARCHAR2(255) NOT NULL,
--    FOREIGN KEY (IdDeAsentamiento) REFERENCES Localidad(Id)
--);


--Registro civil -- Persona y domicilio

CREATE TABLE Persona (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellidoPaterno VARCHAR2(100) NOT NULL,
    apellidoMaterno VARCHAR2(100) NOT NULL,
    fechaDeNacimiento DATE NOT NULL,
    fechaDeFin DATE
);

CREATE TABLE RelacionFamiliar (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    idDepersona NUMBER NOT NULL,
    idDepadre NUMBER, -- Puede ser NULL si no hay padre definido
    idDemadre NUMBER, -- Puede ser NULL si no hay madre definida
    CONSTRAINT fk_relacion_persona FOREIGN KEY (idDepersona) REFERENCES Persona(id) ON DELETE CASCADE,
    CONSTRAINT fk_relacion_padre FOREIGN KEY (idDePadre) REFERENCES Persona(id),
    CONSTRAINT fk_relacion_madre FOREIGN KEY (idDeMadre) REFERENCES Persona(id) 
);


CREATE TABLE TipoDeDomicilio (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(100) NOT NULL
);


---falta ejecutar

CREATE TABLE Domicilio (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdDeFederativa INT NOT NULL,
    IdDeMunicipio INT NOT NULL,
    IdDeLocalidad INT,
    IdDePostal INT, -----AGREGADOS A POSTERIORI, DEBE CREARSE UNA TABLA PARA ESTO
    IdDeColonia INT, ----DEBE CREARSE TABLA PARA ESTO
    numExt INT,
    numInt INT,
    calle VARCHAR2(255),
    CONSTRAINT fk_domicilio_entidad FOREIGN KEY (IdDeFederativa) REFERENCES EntidadFederativa(Id),
    CONSTRAINT fk_domicilio_municipio FOREIGN KEY (IdDeMunicipio) REFERENCES Municipio(Id),
    CONSTRAINT fk_domicilio_localidad FOREIGN KEY (IdDeLocalidad) REFERENCES Localidad(Id),
    CONSTRAINT fk_domicilio_colonia FOREIGN KEY (IdDeColonia) REFERENCES Colonia(Id),
    CONSTRAINT fk_domicilio_postal FOREIGN KEY (IdDePostal) REFERENCES Postal(Id)
);

CREATE TABLE PersonaDomicilio (
    IdDePersona INT NOT NULL,
    IdDeDomicilio INT NOT NULL,
    IdDeTipoDeDomicilio INT,
    fechaDeInicio DATE NOT NULL,
    fechaDeFin DATE,
    PRIMARY KEY (IdDePersona, IdDeDomicilio),
    CONSTRAINT fk_personadomicilio_persona FOREIGN KEY (IdDePersona) REFERENCES Persona(Id),
    CONSTRAINT fk_personadomicilio_domicilio FOREIGN KEY (IdDeDomicilio) REFERENCES Domicilio(Id),
    CONSTRAINT fk_personadomicilio_tipoDeDomicilio FOREIGN KEY (IdDeTipoDeDomicilio) REFERENCES TipoDeDomicilio(Id)
);

--Colegio electoral --- Sistema de partidos 

CREATE TABLE Partido (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    denominacion VARCHAR2(100) NOT NULL,
    siglas VARCHAR2(100) NOT NULL,
    fechaDeInicio DATE NOT NULL,
    fechaDeFin DATE
);

CREATE TABLE Visual(
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdDePartido INT,
    IdDeRecursoVigente INT NOT NULL, 
    IdDeTipoDeVisual INT NOT NULL,
    contenido VARCHAR2(1000),
    CONSTRAINT fk_visual_partido FOREIGN KEY (IdDePartido) REFERENCES Partido(Id)
);

CREATE TABLE RecursoVigente(
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(100) NOT NULL
);

CREATE TABLE TipoDeVisual(
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(100) NOT NULL

);


--Colegio electoral --- Proceso electoral 

CREATE TABLE Proceso (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdDeNivel,
    descripcion VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_proceso_nivel FOREIGN KEY (IdDeNivel) REFERENCES Nivel(Id)
);

CREATE TABLE Nivel (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(100) NOT NULL
);


-----ESTA ES CON VALORES DEFAULT, OPCION A CREAR NUEVA RESTRICCION DENTRO DEL SISTEMA FUTURO

CREATE TABLE ProcesoLugar (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdDeNivel INT NOT NULL,
    IdDeLocalidad INT,
    IdDeEntidad INT,
    IdDeMunicipio INT, 
    CONSTRAINT fk_procesolugar_nivel FOREIGN KEY (IdDeNivel) REFERENCES Nivel(Id),
    CONSTRAINT fk_procesolugar_localidad FOREIGN KEY (IdDeLocalidad) REFERENCES Localidad(Id),
    CONSTRAINT fk_procesolugar_entidad FOREIGN KEY (IdDeEntidad) REFERENCES EntidadFederativa(Id),
    CONSTRAINT fk_procesolugar_municipio FOREIGN KEY (IdDeMunicipio) REFERENCES Municipio(Id)
);

CREATE TABLE InstanciaDeProceso (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdDeProceso INT NOT NULL,
    IdDeNivel INT NOT NULL,
    IdDeProcesoLugar INT NOT NULL, 
    ganadoresNum INT NOT NULL,
    fechaHoraDeInicio DATE NOT NULL,
    fechaHoraDeFin DATE NOT NULL,
    CONSTRAINT fk_instanciadeproceso_proceso FOREIGN KEY (IdDeProceso) REFERENCES Proceso(Id),
    CONSTRAINT fk_instanciadeproceso_nivel FOREIGN KEY (IdDeNivel) REFERENCES Nivel(Id),
    CONSTRAINT fk_instanciadeproceso_procesolugar FOREIGN KEY (IdDeProcesoLugar) REFERENCES ProcesoLugar(Id)
);




--Colegio electoral --- Sujetos electorales

CREATE TABLE Candidatura (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdDeInstanciaDeProceso INT NOT NULL,
    IdDePartido INT NOT NULL,
    voto INT DEFAULT 0,
    CONSTRAINT fk_candidatura_instanciadeproceso FOREIGN KEY (IdDeInstanciaDeProceso) REFERENCES InstanciaDeProceso(Id),
    CONSTRAINT fk_candidatura_partido FOREIGN KEY (IdDePartido) REFERENCES Partido(Id)
);


CREATE TABLE ElectorCandidatura (
    IdDeElector INT NOT NULL,
    IdDeCandidatura INT NOT NULL,
    fechaHoraDeInicio DATE NOT NULL,
    fechaHoraDeFin DATE NOT NULL,
    PRIMARY KEY (IdDeElector, IdDeCandidatura),
    CONSTRAINT fk_electorcandidatura_elector FOREIGN KEY (IdDeElector) REFERENCES Elector(Id),
    CONSTRAINT fk_electorcandidatura_candidatura FOREIGN KEY (IdDeCandidatura) REFERENCES Candidatura(Id)
);

CREATE TABLE Elector (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdDePersona INT NOT NULL,
    fechaDeInicio DATE NOT NULL, 
    fechaDeFin DATE,
    CONSTRAINT fk_elector_persona FOREIGN KEY (IdDePersona) REFERENCES Persona(Id)
);

CREATE TABLE ElectorInstancia(
    IdDeInstanciaDeProceso INT NOT NULL,
    IdDeElector INT NOT NULL,
    fechaHoraDeVoto DATE NOT NULL, 
    CONSTRAINT fk_electorinstancia_instanciadeproceso FOREIGN KEY (IdDeInstanciaDeProceso) REFERENCES InstanciaDeProceso(Id),
    CONSTRAINT fk_electorinstancia_elector FOREIGN KEY (IdDeElector) REFERENCES Elector(Id)

);

--Colegio electoral --- ProcesoElectoral

CREATE TABLE Voto (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdDeInstanciaDeProceso INT NOT NULL,
    IdDeCandidatura INT NOT NULL,
    CONSTRAINT fk_voto_instanciadeproceso FOREIGN KEY (IdDeInstanciaDeProceso) REFERENCES InstanciaDeProceso(Id),
    CONSTRAINT fk_voto_candidatura FOREIGN KEY (IdDeCandidatura) REFERENCES Candidatura(Id)
);


-- Reactivar restricciones de claves foráneas
BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET CONSTRAINTS = IMMEDIATE';
END;
/

-- Confirmar transacciones
COMMIT;



